export const data = [
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 0 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 1 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 2 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 3 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 4 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 5 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 6 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 7 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 8 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 9 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 10 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 11 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 12 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 13 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 14 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 15 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 16 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
  { value: 17 },
];

export const stackedData = [
  { name: 'Blue', color: '#33ACF2', value: 4 },
  { name: 'Blue', color: '#33ACF2', value: 4 },
  { name: 'Blue', color: '#33ACF2', value: 4 },
  { name: 'Blue', color: '#33ACF2', value: 5 },
  { name: 'Blue', color: '#33ACF2', value: 5 },
  { name: 'Blue', color: '#33ACF2', value: 5 },
  { name: 'Blue', color: '#33ACF2', value: 6 },
  { name: 'Blue', color: '#33ACF2', value: 6 },
  { name: 'Blue', color: '#33ACF2', value: 6 },
  { name: 'Blue', color: '#33ACF2', value: 7 },
  { name: 'Blue', color: '#33ACF2', value: 7 },
  { name: 'Blue', color: '#33ACF2', value: 7 },
  { name: 'Blue', color: '#33ACF2', value: 8 },
  { name: 'Blue', color: '#33ACF2', value: 9 },
  { name: 'Blue', color: '#33ACF2', value: 12 },
  { name: 'Blue', color: '#33ACF2', value: 13 },
  { name: 'Blue', color: '#33ACF2', value: 14 },
  { name: 'Blue', color: '#33ACF2', value: 15 },
  { name: 'Blue', color: '#33ACF2', value: 16 },
  { name: 'Blue', color: '#33ACF2', value: 16 },
  { name: 'Blue', color: '#33ACF2', value: 16 },
  { name: 'Blue', color: '#33ACF2', value: 16 },
  { name: 'Blue', color: '#33ACF2', value: 17 },
  { name: 'Blue', color: '#33ACF2', value: 17 },
  { name: 'Blue', color: '#33ACF2', value: 17 },
  { name: 'Blue', color: '#33ACF2', value: 17 },
  { name: 'Blue', color: '#33ACF2', value: 18 },
  { name: 'Blue', color: '#33ACF2', value: 18 },
  { name: 'Blue', color: '#33ACF2', value: 18 },
  { name: 'Blue', color: '#33ACF2', value: 18 },
  { name: 'Blue', color: '#33ACF2', value: 19 },
  { name: 'Blue', color: '#33ACF2', value: 19 },
  { name: 'Blue', color: '#33ACF2', value: 19 },
  { name: 'Blue', color: '#33ACF2', value: 19 },
  { name: 'Blue', color: '#33ACF2', value: 20 },
  { name: 'Blue', color: '#33ACF2', value: 21 },
  { name: 'Blue', color: '#33ACF2', value: 22 },
  { name: 'Blue', color: '#33ACF2', value: 24 },
  { name: 'Blue', color: '#33ACF2', value: 25 },
  { name: 'Blue', color: '#33ACF2', value: 26 },
  { name: 'Green', color: '#04BC7F', value: 0 },
  { name: 'Green', color: '#04BC7F', value: 1 },
  { name: 'Green', color: '#04BC7F', value: 2 },
  { name: 'Green', color: '#04BC7F', value: 3 },
  { name: 'Green', color: '#04BC7F', value: 4 },
  { name: 'Green', color: '#04BC7F', value: 5 },
  { name: 'Green', color: '#04BC7F', value: 6 },
  { name: 'Green', color: '#04BC7F', value: 7 },
  { name: 'Green', color: '#04BC7F', value: 7 },
  { name: 'Green', color: '#04BC7F', value: 9 },
  { name: 'Green', color: '#04BC7F', value: 9 },
  { name: 'Green', color: '#04BC7F', value: 9 },
  { name: 'Green', color: '#04BC7F', value: 9 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 10 },
  { name: 'Green', color: '#04BC7F', value: 11 },
  { name: 'Green', color: '#04BC7F', value: 11 },
  { name: 'Green', color: '#04BC7F', value: 11 },
  { name: 'Green', color: '#04BC7F', value: 11 },
  { name: 'Green', color: '#04BC7F', value: 11 },
  { name: 'Green', color: '#04BC7F', value: 12 },
  { name: 'Green', color: '#04BC7F', value: 12 },
  { name: 'Green', color: '#04BC7F', value: 12 },
  { name: 'Green', color: '#04BC7F', value: 12 },
  { name: 'Green', color: '#04BC7F', value: 13 },
  { name: 'Green', color: '#04BC7F', value: 13 },
  { name: 'Green', color: '#04BC7F', value: 14 },
  { name: 'Green', color: '#04BC7F', value: 14 },
  { name: 'Green', color: '#04BC7F', value: 15 },
  { name: 'Green', color: '#04BC7F', value: 15 },
  { name: 'Green', color: '#04BC7F', value: 16 },
  { name: 'Green', color: '#04BC7F', value: 17 },
  { name: 'Green', color: '#04BC7F', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 4 },
  { name: 'Orange', color: '#FFA217', value: 5 },
  { name: 'Orange', color: '#FFA217', value: 8 },
  { name: 'Orange', color: '#FFA217', value: 8 },
  { name: 'Orange', color: '#FFA217', value: 8 },
  { name: 'Orange', color: '#FFA217', value: 9 },
  { name: 'Orange', color: '#FFA217', value: 9 },
  { name: 'Orange', color: '#FFA217', value: 10 },
  { name: 'Orange', color: '#FFA217', value: 10 },
  { name: 'Orange', color: '#FFA217', value: 11 },
  { name: 'Orange', color: '#FFA217', value: 11 },
  { name: 'Orange', color: '#FFA217', value: 11 },
  { name: 'Orange', color: '#FFA217', value: 12 },
  { name: 'Orange', color: '#FFA217', value: 12 },
  { name: 'Orange', color: '#FFA217', value: 12 },
  { name: 'Orange', color: '#FFA217', value: 13 },
  { name: 'Orange', color: '#FFA217', value: 13 },
  { name: 'Orange', color: '#FFA217', value: 14 },
  { name: 'Orange', color: '#FFA217', value: 14 },
  { name: 'Orange', color: '#FFA217', value: 14 },
  { name: 'Orange', color: '#FFA217', value: 15 },
  { name: 'Orange', color: '#FFA217', value: 15 },
  { name: 'Orange', color: '#FFA217', value: 16 },
  { name: 'Orange', color: '#FFA217', value: 16 },
  { name: 'Orange', color: '#FFA217', value: 16 },
  { name: 'Orange', color: '#FFA217', value: 16 },
  { name: 'Orange', color: '#FFA217', value: 17 },
  { name: 'Orange', color: '#FFA217', value: 17 },
  { name: 'Orange', color: '#FFA217', value: 17 },
  { name: 'Orange', color: '#FFA217', value: 17 },
  { name: 'Orange', color: '#FFA217', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 19 },
  { name: 'Orange', color: '#FFA217', value: 19 },
  { name: 'Orange', color: '#FFA217', value: 18 },
  { name: 'Orange', color: '#FFA217', value: 19 },
  { name: 'Orange', color: '#FFA217', value: 19 },
  { name: 'Orange', color: '#FFA217', value: 19 },
  { name: 'Orange', color: '#FFA217', value: 20 },
  { name: 'Orange', color: '#FFA217', value: 20 },
  { name: 'Orange', color: '#FFA217', value: 21 },
  { name: 'Orange', color: '#FFA217', value: 22 },
  { name: 'Orange', color: '#FFA217', value: 23 },
  { name: 'Orange', color: '#FFA217', value: 23 },
];
